version: "3.8"
name: keycloak
services:
  dev:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    restart: always
    env_file: .env
    environment:
      # Credentials for admin account
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      # Enable health and metrics support
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      # Credentials for storing into an external database
      KC_DB: ${DB_VENDOR}
      KC_DB_URL_HOST: ${DB_HOST}
      KC_DB_URL_PORT: ${DB_PORT}
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - ${APP_PORT}:8080
    # volumes:
    #   - ./backend:/backend
    extra_hosts:
      - host.docker.internal:host-gateway

  prod:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start
    restart: always
    env_file: .env
    environment:
      # Credentials for admin account
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      # Enable health and metrics support
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      # Credentials for storing into an external database
      KC_DB: ${DB_VENDOR}
      KC_DB_URL_HOST: ${DB_HOST}
      KC_DB_URL_PORT: ${DB_PORT}
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - ${APP_PORT}:8080
    # volumes:
    #   - ./backend:/backend
    extra_hosts:
      - host.docker.internal:host-gateway
