version: "3.8"
name: keycloak_db
services:
  prod:
    container_name: ${CONTAINER_NAME}
    image: ${CONTAINER_NAME}:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./backups:/backups
    extra_hosts:
      - host.docker.internal:host-gateway
